version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: etalon
      POSTGRES_PASSWORD: 4ynJm9cM
      POSTGRES_DB: vendas
    volumes:
      - etalon_vendas:/var/lib/postgres

  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

volumes:
  etalon_vendas:
